#define IDD_DIALOG_ANNOTATION  2199
#define	IDC_TEXT_ANNOTATION        1001
#define IDC_EDITTEXT_ANNOTATION    1007
#define IDC_BUTTON_FILE_ANNOTATION      1003
#define IDC_BUTTON_ENSURE_ANNOTATION      1004
#define IDC_BUTTON_EXIT_ANNOTRTION  1008
#define IDC_BUTTON_HELP_ANNOTATION      1006
