#define IDD_PAGE_DELETE            604


#define IDC_DET_PAGE_GROUP_PRESSSTYLE      1001
#define IDC_DET_PAGE_BOX_PRESSSTYLE_ONE    1002
#define IDC_DET_PAGE_BOX_PRESSSTYLE_TWO    1003
#define IDC_DET_PAGE_BOX_PRESSSTYLE_THREE    1004


#define IDC_DET_PAGE_GROUP_YSSF          1005
  
#define IDC_DET_PAGE_TEXT_ONE     1006
#define IDC_DET_PAGE_TEXT_TWO     1007
#define IDC_DET_PAGE_TEXT_THREE    1008
#define IDC_DET_PAGE_TEXT_FOUR    1009
#define IDC_DET_PAGE_TEXT_FIVE   1010

#define IDC_DET_PAGE_COMBO_ONE   1011
#define IDC_DET_PAGE_COMBO_TWO   1012
#define IDC_DET_PAGE_COMBO_THREE   1013
#define IDC_DET_PAGE_COMBO_FOUR 1014
#define IDC_DET_PAGE_COMBO_FIVE  1015

#define IDC_DET_PAGE_COMBO_SIX  1016
#define IDC_DET_PAGE_TEXT_SIX   1017

#define IDC_DET_PAGE_TEXT_SEVEN  1018
#define IDC_DET_PAGE_TEXT_EIGHT  1019
#define IDC_DET_PAGE_TEXT_NINE   1020
#define IDC_DET_PAGE_TEXT_TEN   1021

#define IDS_METHOD_STORE                81
#define IDS_METHOD_NORMAL               82
#define IDS_METHOD_MAXIMUM              83
#define IDS_METHOD_FAST                 84
#define IDS_METHOD_FASTEST              85
#define IDS_METHOD_ULTRA                86

#define IDS_COMPRESS_NON_SOLID 88
#define IDS_COMPRESS_SOLID 89
