#define IDD_DIALOG_FAVCLEARUP              1100

#define IDC_FAVCLEARUP_LISTVIEW            1001


#define IDC_FAVCLEARUP_BUTTON_ADD          1002
#define IDC_FAVCLEARUP_BUTTON_DELETE       1003
#define IDC_FAVCLEARUP_BUTTON_EDIT         1004
#define IDC_FAVCLEARUP_BUTTON_MOVEUP       1005
#define IDC_FAVCLEARUP_BUTTON_MOVEDOWN     1006
#define IDC_FAVCLEARUP_BUTTON_OK           1007
#define IDC_FAVCLEARUP_BUTTON_CHANEL       1008
#define IDC_FAVCLEARUP_BUTTON_HELP         1009


