#define IDD_DIALOG_FAVORITE            1000

#define IDC_FAVORITE_GROUP             1001
#define IDC_FAVORITE_ADD_TEXT          1002
#define IDC_FAVORITE_PRESSFILE_TEXT    1003
#define IDC_FAVORITE_SAY_TEXT          1004

#define IDC_FAVORITE_ADD_EDIT          1005
#define IDC_FAVORITE_PRESSFILE_EDIT    1006
#define IDC_FAVORITE_SAY_EDIT          1007

#define IDC_FAVORITE_BUTTON_OK         1008
#define IDC_FAVORITE_BUTTON_CHANEL     1009
#define IDC_FAVORITE_BUTTON_HELP       1010



