#define IDD_PAGE_FILE            605

#define IDC_FILE_PAGE_GROUP_EDIT 1001

#define IDC_FILE_PAGE_BOX_EDIT_ONE  1002
#define IDC_FILE_PAGE_BOX_EDIT_TWO  1003
#define IDC_FILE_PAGE_BOX_EDIT_THREE 1004
#define IDC_FILE_PAGE_BOX_EDIT_FOUR  1005


