#define IDD_DIALOG_FIND_PROCESS          613


#define IDC_FINDPROCESS_LIST			1000
#define IDC_FINDPROCESS_BUTTON_BACK     1001
#define IDC_FINDPROCESS_BUTTON_PAUSE    1002
#define IDC_FINDPROCESS_BUTTON_CLOSE    1003
#define IDC_FINDPROCESS_BUTTON_HELP     1004

#define IDC_FINDPROCESS_GROUP_PATH      1005
#define IDC_FINDPROCESS_TEXT_PATH       1006

#define IDC_FINDPROCESS_BUTTON_EXTRACT 1007
#define IDC_FINDPROCESS_BUTTON_CHECK   1008
#define IDC_FINDPROCESS_BUTTON_SEARCH  1009

#define IDC_FINDPROCESS_TEXT_TITLE     1010
