#define IDD_DIALOG_FIND            612
#define IDC_FIND_DLG_GROUP_FILENAME 1001
#define IDC_FIND_DLG_TEXT_FILENAME 1002
#define IDC_FIND_DLG_COMBO_FILENAME 1003
#define IDC_FIND_DLG_TEXT_USTRING 1004
#define IDC_FIND_DLG_COMBO_USTRING 1005
#define IDC_FIND_DLG_BOX_NAME_ONE 1006
#define IDC_FIND_DLG_BOX_NAME_TWO 1007
#define IDC_FIND_DLG_BOX_NAME_THREE 1008

#define IDC_FIND_DLG_GROUP_LOCATION 1009
#define IDC_FIND_DLG_TEXT_LOCATION 1010
#define IDC_FIND_DLG_COMBO_LOCATION 1012
#define IDC_FIND_DLG_TEXT_TYPE 1013
#define IDC_FIND_DLG_COMBO_TYPE 1014
#define IDC_FIND_DLG_BOX_LOCATION_ONE 1015
#define IDC_FIND_DLG_BOX_LOCATION_TWO 1016
#define IDC_FIND_DLG_BOX_LOCATION_THREE 1017

#define IDC_FIND_DLG_BUTTON_OK 1018
#define IDC_FIND_DLG_BUTTON_CANCLE 1019
#define IDC_FIND_DLG_BUTTON_SAVE 1020
#define IDC_FIND_DLG_BUTTON_HELP 1021



