#define IDD_PAGE_FMADVANCED              602

#define IDC_ADV_PAGE_GROUP_TIME		   1001
#define IDC_ADV_PAGE_BOX_TIME_ONE	   1002
#define IDC_ADV_PAGE_BOX_TIME_TWO	   1003
#define IDC_ADV_PAGE_BOX_TIMEE_THREE   1004

#define IDC_ADV_PAGE_GROUP_PATH        1005
#define IDC_ADV_PAGE_BOX_PATH_ONE	   1006
#define IDC_ADV_PAGE_BOX_PATH_TWO      1007
#define IDC_ADV_PAGE_BOX_PATH_THREE    1008

#define IDC_ADV_PAGE_GROUP_PROPTREY    1009
#define IDC_ADV_PAGE_BOX_PROPTREY_ONE  1010 
#define IDC_ADV_PAGE_BOX_PROPTREY_TWO  1011
#define IDC_ADV_PAGE_BOX_PROPTREY_THREE 1012

#define IDC_ADV_PAGE_GROUP_DEL        1013
#define IDC_ADV_PAGE_BOX_DEL_ONE      1014
#define IDC_ADV_PAGE_BOX_DEL_TWO      1015
#define IDC_ADV_PAGE_BOX_DEL_THREE    1016

#define IDC_ADV_PAGE_GROUP_OTHER	  1017
#define IDC_ADV_PAGE_BOX_OTHER_ONE    1018
#define IDC_ADV_PAGE_BOX_OTHER_TWO    1019
