#define IDD_PAGE_GENREAL            610


#define IDC_GEN_PAGE_COMBO_FILE            1001
#define IDC_GEN_PAGE_COMBO_UPDATESTYLE     1002
#define IDC_GEN_PAGE_COMBO_PRESSBYTE       1004            

#define IDC_GEN_PAGE_BUTTON_SEARCH         1005

#define IDC_GEN_PAGE_GROUP_PRESSSTYLE      1006
#define IDC_GEN_PAGE_BOX_PRESSSTYLE_ONE    1007
#define IDC_GEN_PAGE_BOX_PRESSSTYLE_TWO    1008
#define IDC_GEN_PAGE_BOX_PRESSSTYLE_THREE  1009

#define IDC_GEN_PAGE_TEXT_FILE             1010
#define IDC_GEN_PAGE_TEXT_UPDATESTYLE      1011
#define IDC_GEN_PAGE_TEXT_PRESSBYTE        1013
#define IDC_GEN_PAGE_TEXT_7ZGS			   1014

#define IDC_GEN_PAGE_GROUP_EDIT            1015
#define IDC_GEN_PAGE_BOX_EDIT_ONE		   1016	
#define IDC_GEN_PAGE_BOX_EDIT_TWO		   1017
#define IDC_GEN_PAGE_BOX_EDIT_THREE		   1018	
#define IDC_GEN_PAGE_BOX_EDIT_FOUR		   1019	
#define IDC_GEN_PAGE_BOX_EDIT_FIVE		   1020	

#define IDC_GEN_PAGE_TEXT_PRESSLEVEL       2021
#define IDC_GEN_PAGE_COMBO_PRESSLEVEL      2022


#define IDS_COMPRESS_SPLIT_CONFIRM_MESSAGE   94
