#define IDD_DIALOG_GUIDE                  2001
#define IDC_TEXT1_STATIC_GUIDE            1100
#define IDC_TEXT2_STATIC_GUIDE            1101
#define IDC_TEXT3_STATIC_GUIDE            1102
#define IDC_TEXT4_STATIC_GUIDE            1103
#define IDC_TEXT5_STATIC_GUIDE            1104
#define IDC_TEXT6_STATIC_GUIDE            1105
#define IDC_BUTTON_NEXT				   1002
#define IDC_BUTTON_FRONT			   1004
#define IDC_GUIDE_REALEASE				   1005
#define IDC_GUIDE_NEWREALEASE			   1006
#define IDC_GUIDE_ADDREALEASE			   1007
#define IDC_BUTTON_CHANEL			   1008
#define IDC_BUTTON_SEARCH              1010
#define IDC_COMBO_REALEASE             1200
#define IDC_COMBO_PRESSNAME            1201
#define IDC_BITMAP_STATIC              1202
#define IDC_GUIDE_BUTTON_HELP          1203

