#define IDD_DIALOG_INFOR            2200


#define IDC_INFOR_GROUP_ONE      1000
#define IDC_INFOR_GROUP_TWO      1001
#define IDC_INFOR_GROUP_THREE    1002
#define IDC_INFOR_GROUP_FOUR     1003
#define IDC_INFOR_GROUP_FIVE     1004
#define IDC_INFOR_GROUP_SIX      1005
#define IDC_INFOR_GROUP_SEVEN    1006
#define IDC_INFOR_GROUP_EIGHT    1007


#define IDC_INFOR_BUTTON_OK      1008
#define IDC_INFOR_BUTTON_CANCEL  1009
#define IDC_INFOR_BUTTON_HELP    1010


#define IDC_INFOR_TEXT_STATIS_STATE   1011
#define IDC_INFOR_TEXT_ACCOMPLISH     1012


#define IDC_INFOR_TEXT_FILE           1013
#define IDC_INFOR_TEXT_FOLDER         1014
#define IDC_INFOR_TEXT_COMPRESSFILE   1015
#define IDC_INFOR_TEXT_FILESIZE        1016
#define IDC_INFOR_TEXT_BUNCHSIZE       1017
#define IDC_INFOR_TEXT_REALSIZE        1018
#define IDC_INFOR_TEXT_FILESPACE       1019
#define IDC_INFOR_TEXT_COMPRES_SRATE    1020
#define IDC_INFOR_TEXT_COMPRESS_SPEED     1021
#define IDC_INFOR_TEXT_COMPRESS_SIZE     1022
#define IDC_INFOR_TEXT_COMPRESS_TIME   1023
#define IDC_INFOR_TEXT_COMPRESS_START   1024


#define IDC_INFOR_TEXT_FILE_VALU             2013
#define IDC_INFOR_TEXT_FOLDER_VALU           2014
#define IDC_INFOR_TEXT_COMPRESSFILE_VALU     2015
#define IDC_INFOR_TEXT_FILESIZE_VALU         2016
#define IDC_INFOR_TEXT_BUNCHSIZE_VALU        2017
#define IDC_INFOR_TEXT_REALSIZE_VALU         2018
#define IDC_INFOR_TEXT_FILESPACE_VALU        2019
#define IDC_INFOR_TEXT_COMPRES_SRATE_VALU    2020
#define IDC_INFOR_TEXT_COMPRESS_SPEED_VALU    2021
#define IDC_INFOR_TEXT_COMPRESS_SIZE_VALU    2022
#define IDC_INFOR_TEXT_COMPRESS_TIME_VALU   2023
#define IDC_INFOR_TEXT_COMPRESS_START_VALU   2024





