#define  IDD_PAGE_BACKUP      606

#define  IDC_BACKUP_PAGE_GROUP_EDIT     1000
#define  IDC_BACKUP_PAGE_BOX_EDIT_ONE   1001
#define  IDC_BACKUP_PAGE_BOX_EDIT_TWO   1002
#define  IDC_BACKUP_PAGE_BOX_EDIT_THREE 1003
#define  IDC_BACKUP_PAGE_BOX_EDIT_FOUR  1004
#define  IDC_BACKUP_PAGE_BOX_EDIT_FIVE  1005
#define  IDC_BACKUP_PAGE_BOX_EDIT_SIX   1006
#define  IDC_BACKUP_PAGE_EDIT_ONE       1007
