#define   IDD_PAGE_COMMENTS           608

#define   IDC_TEXT1_PAGE_COMMENTS        1000
#define   IDC_BUTTON1_PAGE_COMMENTS      1001
#define   IDC_COMBO1_PAGE_COMMENTS       1002
#define   IDC_TEXT2_PAGE_COMMENTS        1003
#define   IDC_EDIT_PAGE_COMMENTS         1004
#define   IDC_BUTTON2_PAGE_COMMENTS      1005
#define   IDC_BUTTON3_PAGE_COMMENTS      1006
#define   IDC_BUTTON4_PAGE_COMMENTS      1007

