#define IDD_PAGE_CONVENTIONAL              601

#define IDC_STATIC_CON_PAGE_PATH		   1001
#define IDC_CON_PAGE_COMBO_PATH			   1002

#define IDC_CON_PAGE_BUTTON_SHOW_TREE      1003
#define	IDC_CON_PAGE_BUTTON_NEW_F		   1004

#define IDC_CON_PAGE_BOX_UPDATE_ONE		   1005
#define IDC_CON_PAGE_BOX_UPDATE_TWO        1006
#define IDC_CON_PAGE_BOX_UPDATE_THREE      1007

#define IDC_CON_PAGE_BOX_COVER_ONE		   1008
#define IDC_CON_PAGE_BOX_COVER_TWO         1009
#define IDC_CON_PAGE_BOX_COVER_THREE       1010
#define IDC_CON_PAGE_BOX_COVER_FOUR        1011

#define IDC_CON_PAGE_GROUP_UPDATE          1012
#define IDC_CON_PAGE_GROUP_COVER		   1013
#define IDC_CON_PAGE_GROUP_OTHER		   1014

#define IDC_CON_PAGE_BOX_OTHER_ONE         1015
#define IDC_CON_PAGE_BOX_OTHER_TWO         1016
#define IDC_CON_PAGE_BOX_OTHER_THREE       1017

#define IDC_CON_PAGE_BUTTON_SAVE           1018
#define IDC_CON_PAGE_TREE				   1019
