#define IDD_PAGE_SENIOR  609 

#define IDC_SEN_PAGE_GROUP_EDIT 1001

#define IDC_SEN_PAGE_TEXT_ONE  1002
#define IDC_SEN_PAGE_TEXT_TWO  1003

#define IDC_SEN_PAGE_EDITTEXT_ONE 1004
#define IDC_SEN_PAGE_EDITTEXT_TWO 1005

#define IDC_SEN_PAGE_BOX_EDIT_ONE 1006
#define IDC_SEN_PAGE_BOX_EDIT_TWO 1007

#define IDC_SEN_PAGE_COMBO_ONE 1008
#define IDC_SEN_PAGE_TEXT_THREE 1009

#define IDS_PASSWORD_USE_ASCII               110
#define IDS_PASSWORD_PASSWORDS_DO_NOT_MATCH  111
#define IDS_PASSWORD_IS_TOO_LONG             112
